apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-auth-sidecar-demo

resources:
  - config.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: k8s-auth-sidecar

images:
  - name: space.maatini/k8s-auth-sidecar
    newTag: "1.0.0"
