apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rr-sidecar-demo

resources:
  - config.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: rr-sidecar

images:
  - name: space.maatini/rr-sidecar
    newTag: "1.0.0"
